ARG GO_VERSION=1.25.5
FROM docker.io/library/golang:${GO_VERSION}-alpine3.21

RUN apk add --no-cache \
    bash \
    build-base \
    curl \
    git \
    linux-headers \
    zig

ENV CGO_ENABLED=1 \
    GOPATH=/go \
    GOMODCACHE=/go/pkg/mod \
    GOCACHE=/root/.cache/go-build

WORKDIR /tmp/dialtone-src
COPY src/go.mod src/go.sum ./
RUN go mod download

WORKDIR /repo/src
CMD ["sh"]
